### ISSUE TITLE
Any help for instructions on using AWS Lambda?

### ISSUE THREAD

**Issue by robabramowitz** [dpguthrie/dbt-cloud-webhooks-pagerduty#2]

**Comment by dpguthrie** [comment]
There’s some instructions at the bottom of the README for an AWS lambda example.  Also, not entirely sure what you mean about the python code missing the `DBT_CLOUD_SERVICE_TOKEN` variable.  This is set as an environment variable in the fly.io runtime, which means that the dbtc client will retrieve and set this [automatically](https://github.com/dpguthrie/dbtc/blob/9d7f9d9c6eaeebc182baa0dd47e577bc762bac42/dbtc/client/base.py#L29)

**Comment by robabramowitz** [comment]
_
